version: '3.9'

services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  trino:
    image: trinodb/trino
    ports:
      - '8080:8080'
    depends_on:
      - minio
    volumes:
      - ./trino/etc:/etc/trino
      - trino-data:/data/trino

  spark:
    image: bitnami/spark
    ports:
      - '4040:4040'
    environment:
      - SPARK_MODE=master

  microservice-a:
    build:
      context: ./microservice-a # ✅ FIXED
    depends_on:
      - trino
    environment:
      - NODE_ENV=development

  # microservice-b:
  #   build:
  #     context: ./microservice-b # ✅ FIXED
  #   depends_on:
  #     - kafka
  #   environment:
  #     - NODE_ENV=development

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  trino-data: