version: "3.8"
services:
  mysql:
    image: mysql:8.4
    container_name: arkham-mysql
    ports:
      - "3306:3306" # host:container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # <--- Add this line

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  microservice-a:
    build:
      context: .
      dockerfile: microservice-a/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      AWS_REGION: us-east-1
    volumes:
      - .:/app
    command: yarn --cwd microservice-a start:dev

  microservice-b:
    build:
      context: .
      dockerfile: microservice-b/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: yarn --cwd microservice-b start:dev

volumes:
  mysql_data:
